//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalScraper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int ID { get; set; }
        public string Symbol1 { get; set; }
        public string Symbol2 { get; set; }
        public string Symbol3 { get; set; }
        public string Symbol4 { get; set; }
        public string Symbol5 { get; set; }
        public string Symbol6 { get; set; }
        public string Symbol7 { get; set; }
        public string Symbol8 { get; set; }
        public string Symbol9 { get; set; }
        public string Symbol10 { get; set; }
        public string CurrentPrice1 { get; set; }
        public string CurrentPrice2 { get; set; }
        public string CurrentPrice3 { get; set; }
        public string CurrentPrice4 { get; set; }
        public string CurrentPrice5 { get; set; }
        public string CurrentPrice6 { get; set; }
        public string CurrentPrice7 { get; set; }
        public string CurrentPrice8 { get; set; }
        public string CurrentPrice9 { get; set; }
        public string CurrentPrice10 { get; set; }
        public string ChangePercent1 { get; set; }
        public string ChangePercent2 { get; set; }
        public string ChangePercent3 { get; set; }
        public string ChangePercent4 { get; set; }
        public string ChangePercent5 { get; set; }
        public string ChangePercent6 { get; set; }
        public string ChangePercent7 { get; set; }
        public string ChangePercent8 { get; set; }
        public string ChangePercent9 { get; set; }
        public string ChangePercent10 { get; set; }
        public string MarketCap1 { get; set; }
        public string MarketCap2 { get; set; }
        public string MarketCap3 { get; set; }
        public string MarketCap4 { get; set; }
        public string MarketCap5 { get; set; }
        public string MarketCap6 { get; set; }
        public string MarketCap7 { get; set; }
        public string MarketCap8 { get; set; }
        public string MarketCap9 { get; set; }
        public string MarketCap10 { get; set; }
        public System.DateTime DateAndTime { get; set; }
    }
}
